version: '3.8'

# Этот файл автоматически подключается к docker-compose.yml при запуске docker-compose
# и переопределяет настройки для режима разработки

services:
  # Добавляем инструменты для отладки и разработки
  postgres:
    ports:
      - "${POSTGRES_PORT:-5432}:5432"  # Открываем порт для доступа из IDE

  api_gateway:
    environment:
      - ENV=development
      - DEBUG=true
    volumes:
      - ./api_gateway:/app:delegated  # Используем delegated для лучшей производительности
      - ./common:/app/common:delegated
    # Включаем отладку и горячую перезагрузку
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload --reload-dir /app --reload-dir /app/common

  auth_service:
    environment:
      - ENV=development
      - DEBUG=true
    volumes:
      - ./auth_service:/app:delegated
      - ./common:/app/common:delegated
    # Включаем отладку и горячую перезагрузку
    ports:
      - "8001:8000"  # Открываем порт для прямого доступа к сервису

  room_service:
    environment:
      - ENV=development
      - DEBUG=true
    volumes:
      - ./room_service:/app:delegated
      - ./common:/app/common:delegated
    # Включаем отладку и горячую перезагрузку
    ports:
      - "8002:8000"  # Открываем порт для прямого доступа к сервису

  achievement_service:
    environment:
      - ENV=development
      - DEBUG=true
    volumes:
      - ./achievement_service:/app:delegated
      - ./common:/app/common:delegated
    # Включаем отладку и горячую перезагрузку
    ports:
      - "8003:8000"  # Открываем порт для прямого доступа к сервису

  competition_service:
    environment:
      - ENV=development
      - DEBUG=true
    volumes:
      - ./competition_service:/app:delegated
      - ./common:/app/common:delegated
    # Включаем отладку и горячую перезагрузку
    ports:
      - "8004:8000"  # Открываем порт для прямого доступа к сервису
